spring:
  application:
    name: graphql-server-demo

graphql:
  servlet:
    maxQueryDepth: 5
  playground:
    enabled: true
    headers:
      Authorization: Bearer abcd
    settings:
      editor.theme: light